---
title: "Publications and Preprints"
description: |
  
---
**Journal Articles**


1. (Submitted) **Gu, Y.** & Durvasula, K. The Relation between Sonority Difference and Gestural Timing in CV Syllables. _Language Sciences_. [Link](http://ssrn.com/abstract=5123048)


**Conference Proceedings**

1. (In press) **Gu, Y.**, Zhao, S., & Liu, W. Automatic Labeling and Acoustic Correlates of Rhoticity. _Proceedings from the Annual Meeting of the Chicago Linguistic Society_. 

2. **Gu, Y.**, Airola, B., Wang, Y., Shao, A., & Durvasula, K. (2025). The CV Coordination in English and Mandarin. _Proceedings of the Linguistic Society of America_ 10 (1): 5916. [Link](https://doi.org/10.3765/plsa.v10i1.5916)


3. **Gu, Y.** & Peters, R. (2024). English Coronal Stop Deletion Is Categorical Not Gradient. _Proceedings of the Linguistic Society of America_ 9 (1). 5700. [Link](https://doi.org/10.3765/plsa.v9i1.5700) 

4. **Gu, Y.** (2023). Mandarin Hai: A Focus Operator. _Proceedings of the 34th North American Conference on Chinese Linguistics_. [Link](https://www.researchgate.net/publication/389889165_Mandarin_HAI_A_Focus_Operator)


5. **Gu, Y.** (2023). Exploring the Effect of Stress on Gestural Coordination. _Proceedings of the Linguistic Society of America (PLSA)_ 8 (1). 5539. [Link](https://doi.org/10.3765/plsa.v8i1.5539)

6. **Gu, Y.** (2020). Mandarin Self-referential Expressions: A Sociolinguistic Study. _Proceedings of the 32nd North American Conference on Chinese Linguistics_, USA, 539-554. [Link](https://www.researchgate.net/publication/389889345_Mandarin_Self-Referential_Expressions_A_Sociolinguistic_Study)

**Book Reviews**

1. **Gu, Y.** (2021). Kate Vieira, Writing for love and money: How migration drives literacy learning in transnational families. Oxford: Oxford University Press, 2019. Pp. 256. Pb. £20. _Language in Society_, 50 (2), 320-321. [Link](https://doi.org/10.1017/S0047404521000026)



